project_id = "swlwhjnwycvjdhgclwlx"

[functions.create-google-doc]
verify_jwt = false

[functions.list-drive-files]
verify_jwt = false

[functions.test-google-connection]
verify_jwt = false

[functions.create-drive-folder]
verify_jwt = false

[functions.track-login]
verify_jwt = false

[functions.pdf-extract-text]
verify_jwt = true

[functions.pdf-compare]
verify_jwt = true

[functions.pdf-add-to-repository]
verify_jwt = true

[functions.pdf-compare-batch]
verify_jwt = true
